version: "3"
# 这个docker compose由几个服务组成
services:
  mysql8: # 服务的名字
    image: mysql:8.0.29 # image的名字
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 设置初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      # 端口映射
      - 13316:3306
