apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-ymt-mysql-pvc
spec:
  storageClassName: webook-ymt
  # 访问模式，控制能不能被多个pod读写
  accessModes:
    # 被一个pod读写
    - ReadWriteOnce
  # 需要什么样的资源
  resources:
    requests:
      storage: 1Gi

  